{{- if .Values.ingress.enabled }}
{{- $files := .Files }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $files.Get .crtFile | b64enc }}
  tls.key: {{ $files.Get .keyFile | b64enc }}
{{- end }}
{{- end }}
